workerPoolSpecs:
   machineSpec:
      machineType: n1-standard-8
      acceleratorType: NVIDIA_TESLA_V100
      acceleratorCount: 1
   replicaCount: 1
   containerSpec:
      imageUri: gcr.io/applied-fusion-374308/gcp_vm_tester