workerPoolSpecs:
   machineSpec:
      machineType: e2-standard-8
      acceleratorType: NVIDIA_TESLA_T4
      acceleratorCount: 1
   replicaCount: 1
   containerSpec:
      imageUri: gcr.io/<project-id>/<docker-img>